/**
 * Plugin Knowledge Base — long-term store of what EQ plugins the user
 * has, what kind they are, and what RTMcompare can do with each one.
 *
 * Two storage tiers:
 *
 *   1. ACTIVE profiles (in `rtmsend-profiles.ts` registry, hand-coded)
 *      Plugins where Send-to-plugin works today. Profile object
 *      describes how to translate RTMcompare's 9-band recs into the
 *      plugin's parameter writes.
 *
 *   2. REFERENCE profiles (this module, `~/.rtm/plugin-knowledge/`)
 *      Captured automatically when a plugin is loaded in RTMsend.
 *      Includes the FULL parameter dump, probed scalings, archetype
 *      tags, and free-form notes. Used for:
 *
 *        a. Tool-aware recommendations — RTMcompare knows what tools
 *           the engineer has and tailors band suggestions to match
 *           ("you have a Pultec — try a 60 Hz CPS boost + 100 Hz
 *           atten" instead of generic "+1 dB at 80 Hz").
 *
 *        b. Archetype matching — given a desired sonic character
 *           (warm LF, surgical mid-cut, airy HF), pick the plugin
 *           whose archetype best fits.
 *
 *        c. "Best plugin for THIS move" — given a specific band move
 *           and the set of plugins the user has, rank by suitability.
 *
 *        d. Documentation — auto-generate a markdown reference of
 *           every plugin we've learned about.
 *
 * Plugins that don't fit RTM's 9-band Send model (Pultec / API 550 /
 * Neve 1073 / Bettermaker EQ232D) STILL get a reference profile —
 * just no active profile. Future RTMcompare versions can use these
 * for archetype-aware analysis even though Send doesn't work.
 */

import * as path from 'path'
import * as fs from 'fs'
import * as os from 'os'
import { Profile } from './rtmsend-profiles'
import { ParameterSnapshot } from './rtmsend-bridge'

// ── Archetype taxonomy ────────────────────────────────────────────────

/**
 * Tags that describe a plugin's character. A plugin can carry multiple
 * tags (Pro-Q 4 is parametric AND mastering-grade AND linear-phase AND
 * mid-side AND dynamic). Recommendations match against the SET of
 * tags, not a single category.
 */
export type ArchetypeTag =
  // Architecture
  | 'parametric'         // N adjustable bands, freq/gain/Q on each
  | 'graphic'            // Fixed-frequency slider EQ (ISO bands)
  | 'console-strip'      // Channel-strip emulation (Neve 1073, SSL E/G/X)
  | 'pultec'             // Boost+atten interaction, fixed/switched freqs
  | 'tilt'               // Single rotation point tonal balance
  | 'air-band'           // Specialty HF band (Maag, Slate Air, NLS Air)
  | 'spline'             // Curve-drawing EQ (Voxengo CurveEQ)

  // Behavior
  | 'dynamic'            // Frequency-dependent compression (TDR Nova, F6)
  | 'mid-side'           // Explicit M/S routing
  | 'linear-phase'       // No phase shift mode
  | 'minimum-phase'      // Standard IIR

  // Coloration / use case
  | 'vintage'            // Analog modeling, harmonic coloration
  | 'transparent'        // Surgical, no character
  | 'mastering-grade'    // Designed for mastering specifically
  | 'mixing'             // Better suited for tracking/mixing than mastering

  // Filter-only specialties
  | 'high-pass'          // Specialty HPF
  | 'low-pass'           // Specialty LPF

  // Source-separation aware
  | 'stem-aware'         // Independent EQ per stem (Vocals/Bass/Drums/Other)

  // Spectral-matching tools — store a reference snapshot internally
  // and apply a continuous learned curve. The curve isn't addressable
  // via discrete band params; user controls only Amount + Smoothing.
  | 'match-eq'           // Ozone Match EQ, Voxengo CurveEQ match mode

/**
 * Why a plugin is a good fit for a given move. Used for showing the
 * user a reason in the "Best plugin for this move" UI.
 */
export interface RecommendationReason {
  plugin_name: string
  score: number        // 0..1 — higher = better fit
  reasoning: string    // human-readable
}

// ── Reference profile schema ──────────────────────────────────────────

/**
 * Full reference data for a single plugin. Generated by probing the
 * loaded plugin once per session. Persists to disk so subsequent
 * launches don't re-probe.
 */
export interface ReferenceProfile {
  /** VST3 createIdentifierString() — stable across paths/versions. */
  plugin_id: string
  /** Display name as the plugin reports it. */
  name: string
  /** Manufacturer / vendor if discoverable. */
  vendor?: string
  /** Total parameter count seen at probe time. */
  parameter_count: number
  /** ISO timestamp of the probe. */
  scanned_at: string
  /** RTMsend version that did the probe — for reproducibility. */
  rtmsend_version: string
  /** Tags describing the plugin's character. */
  archetype_tags: ArchetypeTag[]
  /** The active Profile if one exists (hand-coded or auto-detected),
   *  or null if the plugin doesn't fit RTM's 9-band Send model. */
  active_profile: Profile | null
  /** Full parameter dump at probe time (default values, not user state). */
  raw_parameters: ParameterSnapshot[]
  /** Free-form notes — anything we want to remember about the plugin. */
  notes?: string
}

// ── Storage layer ─────────────────────────────────────────────────────

/**
 * Knowledge entries live under ~/.rtm/plugin-knowledge/. Each plugin
 * gets a single JSON file keyed by a sanitised version of its name
 * (the plugin_id contains characters like '|' which aren't filename-
 * safe across all filesystems).
 */
export function getKnowledgeDir (): string {
  const dir = path.join(os.homedir(), '.rtm', 'plugin-knowledge')
  if (!fs.existsSync(dir)) {
    try { fs.mkdirSync(dir, { recursive: true }) } catch { /* permission denied — callers handle missing dir */ }
  }
  return dir
}

function nameToFilename (name: string): string {
  // Replace anything that isn't [A-Za-z0-9._-] with '_', collapse repeats,
  // trim leading/trailing dots and underscores.
  return name
    .replace(/[^A-Za-z0-9._-]+/g, '_')
    .replace(/^[._]+|[._]+$/g, '')
    .slice(0, 80)  // filesystem cap
}

export function knowledgePathFor (pluginName: string): string {
  return path.join(getKnowledgeDir(), `${nameToFilename(pluginName)}.json`)
}

export function saveReference (entry: ReferenceProfile): void {
  const p = knowledgePathFor(entry.name)
  const tmp = p + '.tmp'
  try {
    fs.writeFileSync(tmp, JSON.stringify(entry, null, 2), 'utf8')
    fs.renameSync(tmp, p)
  } catch (e) {
    try { fs.unlinkSync(tmp) } catch { /* best-effort cleanup */ }
    throw e
  }
}

export function loadReference (pluginName: string): ReferenceProfile | null {
  const p = knowledgePathFor(pluginName)
  if (!fs.existsSync(p)) return null
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8')) as ReferenceProfile
  } catch {
    return null
  }
}

// 5.7.1 v5 HIGH fix: memoize the full plugin-knowledge corpus by
// directory mtime. Pre-fix the renderer's
// `rtmsend-best-plugins-for-bands` IPC fired on every band edit, and
// each call did readdirSync + readFileSync × ~30 JSON files
// synchronously on the main thread. Combined with the 4 s polling
// load this was a major contributor to the spindump's uv_fs_open
// 30 % saturation. Now we only re-read when the directory's mtime
// advances (a new auto-capture / user-recapture writes a file, which
// updates the dir mtime).
let referencesCache: { dirMtime: number; entries: ReferenceProfile[] } | null = null

export function listAllReferences (): ReferenceProfile[] {
  const dir = getKnowledgeDir()
  let dirMtime = 0
  try { dirMtime = fs.statSync(dir).mtimeMs } catch { /* dir missing — treat as empty */ }
  if (referencesCache && referencesCache.dirMtime === dirMtime) {
    return referencesCache.entries
  }
  let files: string[] = []
  try {
    files = fs.readdirSync(dir).filter(f => f.endsWith('.json'))
  } catch { /* dir doesn't exist yet — return empty list */ }
  const out: ReferenceProfile[] = []
  for (const f of files) {
    try {
      const entry = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) as ReferenceProfile
      out.push(entry)
    } catch { /* skip malformed */ }
  }
  referencesCache = { dirMtime, entries: out }
  return out
}

// ── Hand-coded archetype seeds ────────────────────────────────────────

/**
 * Archetype tags for plugins we already have in the active registry.
 * Looked up by name_contains on the plugin name, same convention as
 * profile matching.
 */
const KNOWN_ARCHETYPES: Array<{ name_contains: string; tags: ArchetypeTag[]; notes?: string }> = [
  {
    name_contains: 'Pro-Q 4',
    tags: ['parametric', 'mastering-grade', 'linear-phase', 'minimum-phase', 'mid-side', 'dynamic', 'transparent'],
    notes: 'Mastering-grade parametric. 24 bands. Per-band Stereo Placement. Per-band Dynamics. Linear-phase mode available.',
  },
  {
    name_contains: 'Pro-Q 3',
    tags: ['parametric', 'mastering-grade', 'linear-phase', 'minimum-phase', 'mid-side', 'dynamic', 'transparent'],
    notes: 'Mastering-grade parametric. 24 bands. Per-band Stereo Placement. Per-band Dynamics.',
  },
  {
    name_contains: 'kirchhoff',
    tags: ['parametric', 'mastering-grade', 'linear-phase', 'minimum-phase', 'mid-side', 'dynamic', 'transparent'],
    notes: 'Mastering-grade parametric. 32 bands. Per-band Stereo Placement, Dynamics, Sidechain.',
  },
  {
    name_contains: 'bx_digital',
    tags: ['parametric', 'console-strip', 'mid-side', 'vintage', 'mixing'],
    notes: 'M/S Master mode console-style EQ. 5 named bands per channel (LF/LMF/MF/HMF/HF) plus Bass/Presence Shift.',
  },
  {
    name_contains: 'bx_hybrid',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing'],
    notes: '5-band per channel analog-style EQ. No Q control, no per-band enable.',
  },
  {
    name_contains: 'AUGraphicEQ',
    tags: ['graphic', 'minimum-phase'],
    notes: '31-band ISO graphic EQ. Fixed centre frequencies. ±24 dB.',
  },
  {
    name_contains: 'Ozone 12 Equalizer',
    tags: ['parametric', 'mastering-grade', 'transparent', 'mid-side', 'minimum-phase'],
    notes: '8-band mastering EQ with M/S (Stereo/Main + Aux). Linear freq mapping (unusual).',
  },
  {
    name_contains: 'Ozone 12 Stem EQ',
    tags: ['parametric', 'stem-aware', 'mastering-grade', 'transparent', 'minimum-phase'],
    notes: 'Source-separated EQ. 4 stems (Vocals/Bass/Drums/Other), each with its own 8-band EQ. Reference-only — sending full-mix RTM recs to all stems would 4x the EQ. Future stem-aware recommendations could target a single stem.',
  },
  {
    name_contains: 'Ozone 12 Match EQ',
    tags: ['match-eq', 'mastering-grade', 'transparent', 'mid-side', 'linear-phase'],
    notes: 'Spectral matching EQ. The curve is a learned snapshot — only Amount + Smoothing are addressable via params (no freq/gain/Q). Reference-only. RTMcompare overlaps with this conceptually — both do reference-based spectral matching.',
  },
  {
    name_contains: 'Match EQ',
    tags: ['match-eq', 'transparent'],
    notes: 'Spectral matching EQ — curve not addressable as bands.',
  },
  {
    name_contains: 'SPL PQ',
    tags: ['parametric', 'mastering-grade', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'SPL analog-modelled mastering EQ. 5 named bands per channel with overlapping per-band freq ranges. Q is reversed (high norm = wide Q).',
  },
  {
    name_contains: 'SPL Passeq',
    tags: ['pultec', 'vintage', 'mastering-grade', 'mid-side', 'minimum-phase'],
    notes: 'Pultec-style passive EQ. Separate Boost and Cut knobs per Low/Mid/High band — does NOT fit RTM freq+gain+Q model. Reference-only; no active Send profile.',
  },
  {
    name_contains: 'Ozone',
    tags: ['parametric', 'mastering-grade', 'transparent'],
    notes: 'iZotope Ozone module — version-specific layout.',
  },
  {
    name_contains: 'Sontec MES-432',
    tags: ['parametric', 'mastering-grade', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'Sontec MES-432D9D — high-end mastering EQ emulation. 5 bands per channel: 2 shelves (Lo/Hi) + 3 parametric (Lo/Mid/Hi). Bandwidth-based Q. Auto-detect missed it due to "L"/"R" channel suffixes on param names. Reference-only — active profile would need manual per-band freq probe.',
  },
  {
    name_contains: 'Sontec',
    tags: ['parametric', 'mastering-grade', 'vintage'],
    notes: 'Sontec hardware-emulation mastering EQ.',
  },
  {
    name_contains: 'SurferEQ',
    tags: ['parametric', 'mixing', 'minimum-phase'],
    notes: 'SurferEQ — pitch-tracking parametric EQ. Bands automatically follow the input fundamental pitch. 5 bands. Better suited for tracking/mixing than mastering.',
  },
  {
    name_contains: 'Pultec EQP-1S3',
    tags: ['pultec', 'vintage', 'mastering-grade', 'minimum-phase'],
    notes: 'MixWave Pultec EQP-1S3 — direct emulation of the iconic Pultec EQP-1A. CPS (low) Boost+Atten + Kcs (high) Boost+Atten with Bandwidth. Reference-only.',
  },
  {
    name_contains: 'Pultec',
    tags: ['pultec', 'vintage', 'mastering-grade'],
    notes: 'Pultec EQP-1A-family hardware emulation.',
  },
  {
    name_contains: 'DW Fearn VT-15',
    tags: ['pultec', 'console-strip', 'vintage', 'mastering-grade', 'dynamic', 'minimum-phase'],
    notes: 'MixWave DW Fearn VT-15 — Pultec EQ + integrated compressor (channel-strip layout). Same EQ section as VT-5 (Low/Mid/High Boost+Cut). Reference-only.',
  },
  {
    name_contains: 'DW Fearn VT-5',
    tags: ['pultec', 'vintage', 'mastering-grade', 'minimum-phase'],
    notes: 'MixWave DW Fearn VT-5 — Pultec-style passive tube EQ. Separate Boost+Cut controls per Low/Mid/High band, plus tube saturation. Reference-only — Pultec architecture doesn\'t fit RTM freq+gain+Q model.',
  },
  {
    name_contains: 'Fearn',
    tags: ['pultec', 'vintage', 'mastering-grade'],
    notes: 'DW Fearn analog hardware-style tube EQ.',
  },
  {
    name_contains: 'Black Box Analog Design HG-Q',
    tags: ['pultec', 'console-strip', 'vintage', 'mastering-grade', 'mid-side', 'minimum-phase'],
    notes: 'Black Box HG-Q — Pultec-style boost+cut architecture (separate Boost AND Cut controls per band, each with their own Freq/Q), 3 bands per channel + saturation + parallel mode + ganged frequency linking. Reference-only — does not fit RTM single-Gain-per-band model.',
  },
  {
    name_contains: 'Black Box',
    tags: ['vintage', 'mastering-grade'],
    notes: 'Black Box Analog Design — vintage analog modeling.',
  },
  {
    name_contains: 'Bettermaker EQ232D',
    tags: ['pultec', 'console-strip', 'vintage', 'mastering-grade', 'mid-side', 'minimum-phase'],
    notes: 'Bettermaker EQ232D — hardware-style mastering EQ combining 2 parametric bands + Pultec-style PEQ section. Reference-only.',
  },
  {
    name_contains: 'Bettermaker',
    tags: ['vintage', 'mastering-grade'],
    notes: 'Bettermaker hardware-modeled mastering processor.',
  },
  {
    name_contains: 'AMEK EQ 250',
    tags: ['parametric', 'mastering-grade', 'console-strip', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'AMEK EQ 250 — same Brainworx architecture as EQ 200 (5 bands per channel, Range selector per band), different default frequencies (LF/LMF 120 Hz, MF 1.2 kHz, HMF/HF 3.2 kHz). Reference-only.',
  },
  {
    name_contains: 'AMEK EQ 200',
    tags: ['parametric', 'mastering-grade', 'console-strip', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'AMEK EQ 200 (Plugin Alliance / Brainworx). 5 bands per channel (LF/LMF/MF/HMF/HF) with per-band Range selector (Full/Half) that toggles each band\'s freq zone. Bands have overlapping defaults (LF/LMF both at 80 Hz, HMF/HF both at 1.8 kHz) — Range mode determines actual operating zone. Reference-only — would need custom translation logic that picks Range value per RTM target frequency.',
  },
  {
    name_contains: 'AMEK',
    tags: ['parametric', 'mastering-grade', 'vintage'],
    notes: 'AMEK analog-modeled mastering EQ.',
  },
  {
    name_contains: 'bx_console SSL 4000 E',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing', 'minimum-phase'],
    notes: 'Brainworx bx_console SSL 4000 E (brown EQ). 4-band channel strip, ±15 dB across bands, otherwise same architecture as 4000 G.',
  },
  {
    name_contains: 'bx_console SSL 4000',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing', 'minimum-phase'],
    notes: 'Brainworx bx_console SSL 4000 G. 4-band channel strip EQ with the 4000-series curves (±22 dB mids, Q 3.0..0.5, all linear freq).',
  },
  {
    name_contains: 'bx_console SSL 9000',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing', 'minimum-phase'],
    notes: 'Brainworx bx_console SSL 9000 J — SSL 9000 channel strip emulation. 4-band EQ (Low/Low-Mid/High-Mid/High) with asymmetric gain ranges and reversed Q on parametric mids. Tagged mixing not mastering — this is a tracking/mixing tool.',
  },
  {
    name_contains: 'bx_console',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing'],
    notes: 'bx_console-family channel strip emulation.',
  },
  {
    name_contains: 'museq',
    tags: ['parametric', 'mastering-grade', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'elysia museq — analog-modelled BOOST-ONLY passive mastering EQ. 5 bands per channel (2 shelves + 3 bells). Cuts not addressable — RTM negative-gain moves become no-ops on this plugin.',
  },
  {
    name_contains: 'elysia',
    tags: ['parametric', 'mastering-grade', 'vintage'],
    notes: 'elysia analog-modelled mastering processors.',
  },
  {
    name_contains: 'Knif Audio Soma',
    tags: ['parametric', 'mastering-grade', 'vintage', 'mid-side', 'minimum-phase'],
    notes: 'Knif Audio Soma — Finnish boutique mastering EQ. 4 bands per channel with quirky Bandwidth knob that morphs into shelf mode at max. ±8 dB.',
  },
  {
    name_contains: 'Knif',
    tags: ['parametric', 'mastering-grade', 'vintage'],
    notes: 'Knif Audio analog-modeled mastering EQ.',
  },
  {
    name_contains: 'Lindell EQ825',
    tags: ['parametric', 'console-strip', 'vintage', 'mixing', 'mid-side', 'minimum-phase'],
    notes: 'Plugin Alliance Lindell EQ825 — Pultec/console hybrid. 5 bands per channel (LowShelf/Low/Mid/High/HighShelf), no Q, ±12 dB. Each band has its own narrow freq range. Mid/Side mode available.',
  },
  {
    name_contains: 'Lindell',
    tags: ['parametric', 'console-strip', 'vintage', 'mastering-grade'],
    notes: 'Lindell-family analog-modeled EQ.',
  },
  {
    name_contains: 'Maag EQ4',
    tags: ['graphic', 'air-band', 'mastering-grade', 'vintage', 'minimum-phase'],
    notes: 'Maag EQ4 — 6-band graphic EQ with iconic Air Band (selectable 2.5/5/10/20/40 kHz). ±5 dB per band linear. Default Air = 10 kHz when sent from RTMcompare.',
  },
  {
    name_contains: 'Maag',
    tags: ['graphic', 'air-band', 'vintage', 'mastering-grade'],
    notes: 'Maag-family EQ — fixed-frequency bands, distinctive Air Band character.',
  },
  {
    name_contains: 'NSEQ',
    tags: ['parametric', 'console-strip', 'vintage', 'mastering-grade', 'mid-side', 'minimum-phase'],
    notes: 'Millennia NSEQ-2 audiophile mastering EQ. 4 bands per channel (2 shelves + 2 parametric). Tube/Solid-State topology toggle. Has "Frequency X10" multiplier per parametric band that shifts freq range by 10x. Reference-only — sparse band count + X10 toggle requires custom translation logic.',
  },
  {
    name_contains: 'Millennia',
    tags: ['parametric', 'vintage', 'mastering-grade'],
    notes: 'Millennia analog-modeled mastering processor.',
  },
]

export function inferArchetype (pluginName: string): { tags: ArchetypeTag[]; notes?: string } {
  const needle = pluginName.toLowerCase()
  for (const a of KNOWN_ARCHETYPES) {
    if (needle.includes(a.name_contains.toLowerCase())) {
      return { tags: a.tags, notes: a.notes }
    }
  }
  // Heuristics for plugins we don't know about by name. Caller will
  // refine these from the auto-detect output (e.g. if we found
  // numbered bands, the plugin is 'parametric').
  if (needle.includes('graphic')) return { tags: ['graphic', 'minimum-phase'] }
  if (needle.includes('pultec')) return { tags: ['pultec', 'vintage'] }
  if (needle.includes('1073') || needle.includes('neve')) return { tags: ['console-strip', 'vintage'] }
  if (needle.includes('ssl') && needle.includes('eq')) return { tags: ['console-strip'] }
  if (needle.includes('550') && needle.toLowerCase().includes('api')) return { tags: ['console-strip', 'vintage'] }
  if (needle.includes('curve') && needle.includes('eq')) return { tags: ['spline', 'mastering-grade'] }
  if (needle.includes('niveau') || needle.includes('tilt')) return { tags: ['tilt'] }
  if (needle.includes('maag')) return { tags: ['parametric', 'air-band', 'vintage'] }
  if (needle.includes('dyneq') || needle.includes('dynamic eq')) return { tags: ['parametric', 'dynamic'] }
  return { tags: [] }
}
