#!/usr/bin/env python3
"""Generate the renderer-side TypeScript spec registry mirror."""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
OUT = ROOT / "src" / "specs.ts"

sys.path.insert(0, str(PYTHON_DIR))

from specs import SPECS_VERSION, to_json  # noqa: E402


def main() -> None:
    payload = to_json()
    specs_json = json.dumps(payload, indent=2, sort_keys=False)
    contents = f"""/* eslint-disable */
// AUTO-GENERATED by scripts/generate_specs.py. Do not edit by hand.

export interface Spec {{
  id: string
  name: string
  version: string
  published: string
  revised: string | null
  targets: Record<string, unknown>
  references: string[]
  provisional: boolean
}}

export const SPECS_VERSION = {SPECS_VERSION} as const

export const SPECS = {specs_json} as const satisfies Record<string, Spec>

export type SpecId = keyof typeof SPECS
"""
    OUT.write_text(contents, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(payload)} specs, version {SPECS_VERSION})")


if __name__ == "__main__":
    main()
